#!/usr/bin/env python2

from __future__ import print_function
from bs4 import BeautifulSoup as bs
import requests
import sys
import os

def readConfig():
    confPath = os.path.expanduser("~")
    confFile = os.path.join(confPath, ".forcecode")

    if not os.path.isfile(confFile):
        fileI = open(confFile, "w")
        fileI.write("editor:gedit:")
        fileI.write("path:~/.forceCode/:")
        fileI.close()
        return ('gedit','~/.forceCode/')

    else:
        file = open(confFile, "r")
        data = file.read()
        data = data.split(':')
        return (data[1], data[3])

class ForceCoders:

    def __init__(self):
        """
        Initializes the class
        """
        self.round = raw_input("Enter the round number : ")
        assert self.round.isdigit()
        self.url = r"http://codeforces.com/contest/" + str(self.round) + r"/problems"
        self.editor, self.tempPath = readConfig()

        print("Waiting to Connect to CodeForces...")
        self.soup = bs(requests.get(self.url).text)
        print("Round " + self.round + " Connected!")

        self.tmpPath = os.path.expanduser(os.path.join(self.tempPath + str(self.round)))

        self.data = [{}]
        self.input = []
        self.output = []

        self.doIt()

    def doIt(self):
        self.getIO()
        self.getQuestion()
        self.saveData()
        #bl.showAll()


    def getIO(self):
        """
        Parses input/output data from self.soup
        """
        di = self.soup.findAll('div',{'class' : 'input'})
        do = self.soup.findAll('div',{'class' : 'output'})

        for x, y in zip(di, do):
            t1 = str(x).replace("<div class=\"input\"><div class=\"title\">Input</div><pre>","")
            t1 = t1.replace("<br/>","\n").replace("</pre></div>","")
            t2 = str(y).replace("<div class=\"output\"><div class=\"title\">Output</div><pre>","")
            t2 = t2.replace("<br/>","\n").replace("</pre></div>","")

            self.input.append(t1)
            self.output.append(t2)

    def getQuestion(self):
        """
        Parses Question from self.soup
        """
        t1 = []
        for x in self.soup.findAll('div', {'class' : 'title'}):
            t1.append(x.text)

        currQues = -1

        while len(t1) > 0:
            if t1[0] == "Input":
                try:
                    try:
                        self.data[currQues]["input"].append(self.input[0])
                        self.data[currQues]["output"].append(self.output[0])
                    except:
                        self.data[currQues]["input"] = []
                        self.data[currQues]["output"] = []
                        self.data[currQues]["input"].append(self.input[0])
                        self.data[currQues]["output"].append(self.output[0])
                finally:
                    self.input.pop(0)
                    self.output.pop(0)
                    t1.pop(0)

            elif t1[0] == "Output":
                t1.pop(0)

            else:
                currQues += 1
                self.data[currQues]["question"] = t1[0]
                t1.pop(0)
                self.data.append({})

        self.data.pop()

        i = 0
        for t1 in self.soup.findAll('div', {'class' : 'problem-statement'}):
            full_quest = ""
            for quest in t1.findAll('p'):
                full_quest = full_quest + '\n' + quest.text
            self.data[i]["detail"] = full_quest
            i += 1

    def showAll(self):
        """
        Show All data on screen
        """
        for dat in self.data:
            print("Question : ")
            print(dat["question"])
            print(dat["detail"])
            print("Input : ")
            for x in dat["input"]:
                print(x)
            print("Output : ")
            for x in dat["output"]:
                print(x)
            raw_input("Press Any Key...")

    def saveData(self):
        """
        Save data to Disk
        """
        fileN = ""
        for tgn in xrange(len(self.data)):

            tg = chr(ord('A') + tgn)
            tagPath = os.path.join(self.tmpPath, tg)

            if not os.path.exists(tagPath):
                os.makedirs(tagPath)

            inputFile = os.path.join(tagPath, "input.txt")
            outputFile = os.path.join(tagPath, "output.txt")
            cppFile = os.path.join(tagPath, "program" + tg + ".cpp")

            fileI = open(inputFile, "w")
            for x in self.data[tgn]["input"]:
                try:
                    fileI.write(x)
                except:
                    fileI.write(x.encode('utf8'))
            fileI.close()

            fileO = open(outputFile, "w")
            for x in self.data[tgn]["output"]:
                try:
                    fileO.write(x)
                except:
                    fileO.write(x.encode('utf8'))
            fileO.close()

            fileC = open(cppFile, "w")
            fileC.write("/*\n")
            try:
                fileC.write(self.data[tgn]["question"])
            except:
                fileC.write(self.data[tgn]["question"].encode('utf8'))
            try:
                fileC.write(self.data[tgn]["detail"])
            except:
                fileC.write(self.data[tgn]["detail"].encode('utf8'))
            fileC.write("\n*/\n\n")

            fileC.close()

            fileN = fileN + " " + cppFile

        print("All files save to : " + self.tmpPath + ".")

        if self.editor != "NONE":
            print("Opening All files in " + self.editor + " editor.")
            os.system(self.editor + " " + fileN)
            

bl = ForceCoders()
